import tkinter as tk
from tkinter import ttk, messagebox, Tk, Canvas, Entry, Text, Button, PhotoImage, Toplevel
from pathlib import Path
from db import Database
from gui import TuMontallantasApp

class Login:
    def __init__(self, root):
        ##INTERFAZ GRÁFICA
        # This file was generated by the Tkinter Designer by Parth Jadhav
        # https://github.com/ParthJadhav/Tkinter-Designer
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"build/assets/frame0")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)
        
        self.root = root
        self.root.title("TuMontallantas - Ingresa")
        self.root.configure(bg = "#D9D9D9")
        self.root.geometry("400x220+600+400") #Dimensiones de la ventana y posicion

        # Configuración de la ventana principal
        self.frame = ttk.Frame(root, padding="5")
        self.frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))

        self.canvas = Canvas(
            root,
            bg = "#FFFFFF",
            height = 220,
            width = 400,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        self.canvas.place(x = 0, y = 0)

        self.button_image_1 = PhotoImage(file=relative_to_assets("btnEntrar.png"))
        self.btnLogin = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.login,
            relief="flat"
        )
        self.btnLogin.place(
            x=20.0,
            y=150.0,
            width=360.0,
            height=55.0
        )
        self.entry_image_1 = PhotoImage(file=relative_to_assets("txtUbicacion.png"))
        self.entry_bg_1 = self.canvas.create_image(
            200.0,
            115.0,
            image=self.entry_image_1
        )
        self.txtUsuario = Entry(
            bd=0,
            bg="#D9D9D9",
            fg="#000716",
            highlightthickness=0
        )
        self.txtUsuario.place(
            x=30.0,
            y=90.0,
            width=340.0,
            height=25.0
        )
        #txtUsuario.configure(state = "readonly")
        self.canvas.create_text(
            20.0,
            70.0,
            anchor="nw",
            text="Ingresa el usuario:",
            fill="#000000",
            font=("Inter", 12 * -1)
        )
        self.canvas.create_rectangle(
            0.0,
            0.0,
            400.0,
            50.0,
            fill="#D9D9D9",
            outline="")
        self.canvas.create_text(
            20.0,
            13.0,
            anchor="nw",
            text="BIENVENIDO A TUMONTALLANTAS",
            fill="#444444",
            font=("Inter Bold", 18 * -1)
        )
        self.image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(
            375.0,
            27.0,
            image=self.image_image_1
        )
    ################################
    def conectar_bd(self):
        db = Database("usuarios.db")
        db.create_table("usuarios", {"id": "INTEGER PRIMARY KEY", "nombre": "TEXT"})
        #db.insert_data("usuarios", {"nombre": "Javier"})
        #db.insert_data("usuarios", {"nombre": "Pedro"})
        db.close()
    ########################################################################
    def login(self):
        db = Database("usuarios.db")
        usuarios = db.query_data("usuarios")
        for usuario in usuarios:
            if self.txtUsuario.get() == usuario[1]:
                ##self.root.destroy()
                TuMontallantasApp(self.root)
                return
            else:
                self.txtUsuario.delete(0, tk.END)
                self.txtUsuario.insert(0, f"El usuario: {usuario[1]} no está registrado :(")
        db.close()